[package]
name = "preconf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
commit-boost = { path = "../../bin" }

# async / threads
tokio.workspace = true

# serialization
serde.workspace = true

# telemetry
tracing.workspace = true
prometheus.workspace = true

# misc
eyre.workspace = true
color-eyre.workspace = true
lazy_static.workspace = true
