chain = "Holesky"

[pbs]
port = 18550
relay_check = true
timeout_get_header_ms = 950
timeout_get_payload_ms = 4000
timeout_register_validator_ms = 3000
skip_sigverify = true
min_bid_eth = 0.0

late_in_slot_time_ms = 2000

[[relays]]
id = "preconf-relay"
url = "http://0xa55c1285d84ba83a5ad26420cd5ad3091e49c55a813eee651cd467db38a8c8e63192f47955e9376f6b42f6d190571cb5@127.0.0.1:9062"
headers = { X-MyCustomHeader = "MyCustomValue" }
enable_timing_games = false
target_first_request_ms = 200
frequency_get_header_ms = 300

[signer]
[signer.loader]
key_path = "./keys.example.json"
# keys_path = ""
# secrets_path = ""

[metrics]
prometheus_config = "./docker/prometheus.yml"
use_grafana = true

[[modules]]
id = "PRECONF"
type = "preconf"
docker_image = "test_preconf"
